default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: root
  password: root
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: zimouber_vendas_development

test:
  <<: *default
  database: zimouber_vendas_test

production:
  <<: *default
  database: zimouber_vendas_production
